import { AuthContextProvider } from "@/context/AuthContext";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeContext } from "@/context/ThemeContext";
import { AdminContextProvider } from "@/context/AdminContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <ThemeContext>
          <AdminContextProvider>
            <body className={inter.className}>{children}</body>
          </AdminContextProvider>
        </ThemeContext>
      </AuthContextProvider>
    </html>
  );
}
